##### <img src="../SDSS-Logo.png" style="display:inline; width:500px" />


## Learning Objectives
1. Understand broadcasting of numpy arrays



In [1]:
import numpy as np

##### Broadcasting refers to the way Numpy allows operations between ndarrrays of different shapes, as long as they satisy some conditions.
##### Broadcasting is an important feature of Numpy, as it allows for some very efficient computation without using unncessary memory.
##### Some good  references for this lesson are [PLYMI](https://www.pythonlikeyoumeanit.com/module_3.html), [Vanderplas's book](https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html) and the [Numpy docs](https://numpy.org/doc/stable/reference/arrays.ndarray.html).

#####  Example 1
##### Below is a very simple example of broadcasting.

##### You can imagine that the scalar value is duplicated to the same shape as `x1` and added to `x1`

In [2]:
x1 = np.array(range(8))
print(x1)
print(x1 + 10)

[0 1 2 3 4 5 6 7]
[10 11 12 13 14 15 16 17]


##### Example 2
##### Consider that you have 4 observations, with each observation consisting of 3 measurements.
##### You want to subtract the average of each measurement from all the observations.

In [3]:
# 4 observations of 3 measurements can be represented by a 4 X 3 ndarray
my_data = np.random.normal(10, 3, (4,3))
print(my_data)

[[14.26868502  9.6375515   8.84279182]
 [11.90850403  7.05280026 12.38387661]
 [17.49361887 11.34178113 12.99045207]
 [ 5.22239832 11.65213607  3.62046385]]


In [4]:
# The average of each measurement can be found using the np.mean function
measurement_mean = np.mean(my_data, axis=0) # axis=0 -> by column. axis=1 -> by row
print(measurement_mean)

[12.22330156  9.92106724  9.45939609]


In [5]:
# Subtract the mean for each measurement from the measurement for each observation
# In the case the 1 X 3 measurement_mean is being broadcast to 4 X 3.
my_data_nomean = my_data - measurement_mean
print(my_data_nomean)

[[ 2.04538346 -0.28351574 -0.61660427]
 [-0.31479753 -2.86826698  2.92448052]
 [ 5.27031731  1.42071389  3.53105598]
 [-7.00090324  1.73106883 -5.83893224]]


### Compatibility of two ndarrays for broadcast operation is explained by the following from PLYMI.
### Rules of broadcasting:
> To determine if two arrays are broadcast-compatible, align the entries of their shapes such that their trailing dimensions are aligned, and then check that each pair of aligned dimensions satisfy either of the following conditions:
>
>the aligned dimensions have the same size
>
>one of the dimensions has a size of 1
>
>The two arrays are broadcast-compatible if either of these conditions are satisfied for each pair of aligned dimensions.

### A more complicated example broadcasting

### `x2` is a 3 X 1 X 2 array

In [6]:
x2 = np.random.randint(0, 15, size = (3, 1, 2))
print(x2)

[[[13 13]]

 [[ 7 11]]

 [[ 6 14]]]


### `x3` is 3 X 1 array

In [7]:
x3 = np.array([-1, 1, -1]).reshape(3,1)
print(x3)

[[-1]
 [ 1]
 [-1]]


### Any element-wise operation involving `x2` and `x3` will result in a 3 X 3 X 2 array

In [8]:
x4 = x2*x3
print(f"{x4}\n")
print(x4.shape)

[[[-13 -13]
  [ 13  13]
  [-13 -13]]

 [[ -7 -11]
  [  7  11]
  [ -7 -11]]

 [[ -6 -14]
  [  6  14]
  [ -6 -14]]]

(3, 3, 2)


### In the above case, the resulting product after broadcasting is (3, 3, 2)

### Returning to the previous example:

In [9]:
print(x2)
np.broadcast_to(x2, (3,3,2))

[[[13 13]]

 [[ 7 11]]

 [[ 6 14]]]


array([[[13, 13],
        [13, 13],
        [13, 13]],

       [[ 7, 11],
        [ 7, 11],
        [ 7, 11]],

       [[ 6, 14],
        [ 6, 14],
        [ 6, 14]]], dtype=int32)

In [ ]:
np.broadcast_to(x3, (3,3,2))

array([[[-1, -1],
        [ 1,  1],
        [-1, -1]],

       [[-1, -1],
        [ 1,  1],
        [-1, -1]],

       [[-1, -1],
        [ 1,  1],
        [-1, -1]]])

: 

### A nice illustration of broadcasting from [vanderplas's book.](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html)

<img src="Unit-5-6-Fig1.png" width="300" style="float: left" />