##### <img src="../SDSS-Logo.png" style="display:inline; width:500px" />


## Learning Objectives
1. Understand broadcasting of numpy arrays



In [1]:
import numpy as np

### Broadcasting refers to the way Numpy allows operations between ndarrrays of different shapes, as long as they satisy some conditions.
### Broadcasting is an important feature of Numpy, as it allows for some very efficient computation without using unncessary memory.
### Some good  references for this lesson are [PLYMI](https://www.pythonlikeyoumeanit.com/module_3.html), [Vanderplas's book](https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html) and the [Numpy docs](https://numpy.org/doc/stable/reference/arrays.ndarray.html).

###  Example 1
### Below is a very simple example of broadcasting.

### You can imagine that the scalar value is duplicated to the same shape as `x1` and added to `x1`

In [11]:
x1 = np.array(range(8))
x1 + 10

array([10, 11, 12, 13, 14, 15, 16, 17])

### Example 2
### Consider that you have 4 observations, with each observation consisting of 3 measurements.
### You want to subtract the average of each measurement from all the observations.

In [13]:
# 4 observations of 3 measurements can be represented by a 4 X 3 ndarray
my_data = np.random.normal(10, 2, (4,3))
print(my_data)

[[ 7.51752178 11.39468149 11.64747359]
 [ 7.13016943  5.7754509  10.45465929]
 [11.03932985 13.80796145 10.7313594 ]
 [10.39215901 12.31383238 14.43228064]]


In [14]:
# The average of each measurement can be found using the np.mean function
measurement_mean = np.mean(my_data, axis=0)
print(measurement_mean)

[ 9.01979502 10.82298156 11.81644323]


In [5]:
# Subtract the mean for each measurement from the measurement for each observation
# In the case the 1 X 3 measurement_mean is being broadcast to 4 X 3.
my_data_nomean = my_data - measurement_mean
print(my_data_nomean)

[[ 0.72904598 -1.55261734 -0.04857876]
 [-0.25011319  2.04173434 -0.02553066]
 [ 0.88890175 -0.28077281  1.86799073]
 [-1.36783454 -0.20834419 -1.79388131]]


### Compatibility of two ndarrays for broadcast operation is explained by the following from PLYMI.
### Rules of broadcasting:
> To determine if two arrays are broadcast-compatible, align the entries of their shapes such that their trailing dimensions are aligned, and then check that each pair of aligned dimensions satisfy either of the following conditions:
>
>the aligned dimensions have the same size
>
>one of the dimensions has a size of 1
>
>The two arrays are broadcast-compatible if either of these conditions are satisfied for each pair of aligned dimensions.

### A more complicated example broadcasting

### `x2` is a 3 X 1 X 2 array

In [15]:
x2 = np.random.randint(0, 15, size = (3, 1, 2))
print(x2)

[[[12 12]]

 [[12  8]]

 [[ 4  8]]]


### `x3` is 3 X 1 array

In [16]:
x3 = np.array([-1, 1, -1]).reshape(3,1)
print(x3)

[[-1]
 [ 1]
 [-1]]


### Any element-wise operation involving `x2` and `x3` will result in a 3 X 3 X 2 array

In [8]:
x4 = x2*x3
print(f"{x4}\n")
print(x4.shape)

[[[ -4  -3]
  [  4   3]
  [ -4  -3]]

 [[ -4  -3]
  [  4   3]
  [ -4  -3]]

 [[ -9 -12]
  [  9  12]
  [ -9 -12]]]

(3, 3, 2)


### In the above case, the resulting product after broadcasting is (3, 3, 2)

### Returning to the previous example:

In [17]:
print(x2)
np.broadcast_to(x2, (3,3,2))

[[[12 12]]

 [[12  8]]

 [[ 4  8]]]


array([[[12, 12],
        [12, 12],
        [12, 12]],

       [[12,  8],
        [12,  8],
        [12,  8]],

       [[ 4,  8],
        [ 4,  8],
        [ 4,  8]]], dtype=int32)

In [10]:
np.broadcast_to(x3, (3,3,2))

array([[[-1, -1],
        [ 1,  1],
        [-1, -1]],

       [[-1, -1],
        [ 1,  1],
        [-1, -1]],

       [[-1, -1],
        [ 1,  1],
        [-1, -1]]])

### A nice illustration of broadcasting from [vanderplas's book.](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html)

<img src="Unit-5-6-Fig1.png" width="300" style="float: left" />