# Graded: 7 of 7 correct
- [x] Array `A`: (3,3) random ints
- [x] Array `b`: (3,) random ints
- [x] `A * b`
- [x] Explanation of `A * b`: show broadcast versions
- [x] Array `c`: (2,) random ints
- [x] `A * c`
- [x] Explanation of `A * c`

Comments:


## Unit 5 Numpy_Broadcast Quiz
* The objective of this quiz is to understand how to use how broadcasting works with Numpy arrays.

In [1]:
## Import Numpy and check version
import numpy as np
print(f"Numpy version is {np.__version__}")

Numpy version is 2.0.1


## Broadcasting is a feature of Numpy arrays that allows arithmetic operations between arrays that are not necessarily of compatible dimension for the computation.
* During such an operation, the arrays are "broadcast" to a certain size that makes the operartion possible.
* Knowledge of broadcasting is useful in a number of places, for example deep learning methids.

## Create  a Numpy array `A` as a (3, 3) array of random integers.

In [2]:
A = np.random.randint(0, 10, (3, 3))
print(f"A shape is {A.shape} \nand has data: \n{A}")

A shape is (3, 3) 
and has data: 
[[6 9 9]
 [5 8 7]
 [3 2 6]]


## Create a second numpy array, `b` of size (3,) of random integers.

In [3]:
b = np.random.randint(0, 10, (3,))
print(f"b shape is {b.shape} \nand has data: \n{b}")

b shape is (3,) 
and has data: 
[3 2 6]


## Perform the operation `A*b`

In [ ]:
Ab = A * b
print(Ab)

## Explain why it was possible to compute `A*b` in the above case. 
* As part of your explanation, show the broadcast versions of `A` and `b`

### Explanation here.

When we want to compute A*b, the most important thing is the dimension of each matrix, it has to have the same dimension between col dimension of matrix A with rown dimension of matrix b  OR<br />
with the given matrix <b>A[i x j]</b> and <b>b[m x n]</b> where <b>j=m</b>. <br />The way we run the operation is by multiplying A with b starting with the first row of matrix A with row of matrix b.


## Now create a third array `c` that is a (2,) array of random integers.

In [5]:
# Your code here

## Perform the operation `A*c`

In [6]:
# Your code here

## Explain, in terms of broadcasting, why it was not possible to compute `A*c`

### Your explanation here.