## Unit 5 Numpy_Random_Matrix Quiz
* The objective of this quiz is to use Numpy for generating random values and look at simple array manipulation.

In [1]:
## Import Numpy and check version
import numpy as np
print(f"Numpy version is {np.__version__}")

Numpy version is 2.0.1


### Random numbers are frequently used in Data Science.
* Generating random numbers (or rather pseudo-random numbers) is an important function.
* Numpy provides a random number module called `numpy.random`.
* You can learn more about generating random numbers [here](https://numpy.org/doc/stable/reference/random/index.html) and [here](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html#numpy.random.Generator.random).

### Create a random number generator called `my_rng` using the `default_rng()` method in `np.random`. Use the default seed.

In [2]:
# Write your code below.
my_rng = np.random.default_rng()
my_rng.random()

0.4143000627560298

### Now use `my_rng` to generate a 3X3 numpy array of random values.
* Print out this array

In [3]:
# Write your code below.
my_rng.random((3,3))

array([[0.94208485, 0.97272006, 0.09241562],
       [0.44770273, 0.91069362, 0.99748499],
       [0.90883154, 0.9030687 , 0.11638183]])

### What is the distribution of the random numbers generated and what is the range?
* This is not something to be computed, simply look up this information in the [`np.random` web page](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html).

the random number generator default will generate random float64 (default) number within range [0, 1] from "continues uniform" distribution

### Use the Numpy array created above to create a second Numpy array of random numbers that is between -10.0 and 10.0.
* This question requires you to figure out the mapping that will convert a set of random numbers that are distributed as found in the previous question to have the range from -10.0 to 10.0.
* The form of the distributon does not change.

In [4]:
20 * my_rng.random((3,3)) - 10

array([[ 6.18120199,  8.72606017,  9.4692802 ],
       [-1.20852564, -3.11099243,  6.80027866],
       [-8.47244638,  2.61190044,  1.91210842]])

### `np.random` can also generate random integers. Generate a 3X3 array of random integers between 0 and 10.

In [5]:
(10 * my_rng.random((3,3))).astype(int)

array([[6, 6, 6],
       [3, 9, 4],
       [8, 7, 7]])

In [6]:
# OR
my_rng.integers(0, 10, (3, 3))

array([[9, 8, 8],
       [5, 1, 0],
       [4, 8, 4]])

### `np.random` can also generate various common distributions. Generate a 3X3 array of numbers from a normal distribution with mean 10 and standard deviation 2.

In [7]:
gm3 = my_rng.normal(10, 2, (3,3))
gm3

array([[12.9511821 ,  8.80722833,  9.20074442],
       [ 8.78428977,  8.28584956,  8.38662181],
       [11.59097165, 11.5679472 ,  9.68718487]])

### Call the 3X3 matrix of normal random variables generated in the last step `gm3`.
* Use Numpy methods to create two other numpy arrays, `row_sum` and `col_sum`:
* `row_sum` should be the length 3 array of the sum of the rows of `gm3`.
* `col_sum` should be the length 3 array of the sum of the columns of `gm3`

In [12]:
row_sum = gm3.sum(axis=1)
col_sum = gm3.sum(axis=0)
print(f"row_sum: {row_sum} \ncol_sum: {col_sum}")

row_sum: [30.95915486 25.45676113 32.84610372] 
col_sum: [33.32644352 28.66102509 27.2745511 ]
