# Graded: 7 of 7 correct
- [x] Array `A`: (3,3) random ints
- [x] Array `b`: (3,) random ints
- [x] `A * b`
- [x] Explanation of `A * b`: show broadcast versions
- [x] Array `c`: (2,) random ints
- [x] `A * c`
- [x] Explanation of `A * c`

Comments:


## Unit 5 Numpy_Broadcast Quiz
* The objective of this quiz is to understand how to use how broadcasting works with Numpy arrays.

In [1]:
## Import Numpy and check version
import numpy as np
print(f"Numpy version is {np.__version__}")

Numpy version is 2.0.1


## Broadcasting is a feature of Numpy arrays that allows arithmetic operations between arrays that are not necessarily of compatible dimension for the computation.
* During such an operation, the arrays are "broadcast" to a certain size that makes the operartion possible.
* Knowledge of broadcasting is useful in a number of places, for example deep learning methids.

## Create  a Numpy array `A` as a (3, 3) array of random integers.

In [2]:
A = np.random.randint(0, 10, (3, 3))
print(f"A shape is {A.shape} \nand has data: \n{A}")

A shape is (3, 3) 
and has data: 
[[8 6 8]
 [6 5 0]
 [7 5 8]]


## Create a second numpy array, `b` of size (3,) of random integers.

In [3]:
b = np.random.randint(0, 10, (3,))
print(f"b shape is {b.shape} \nand has data: \n{b}")

b shape is (3,) 
and has data: 
[3 9 4]


## Perform the operation `A*b`

In [4]:
Ab = A * b
print(Ab)

[[24 54 32]
 [18 45  0]
 [21 45 32]]


## Explain why it was possible to compute `A*b` in the above case. 
* As part of your explanation, show the broadcast versions of `A` and `b`

### Explanation here.

When we want to compute A*b, the most important thing is the dimension of each matrix, it has to have the same dimension between col dimension of matrix A with rown dimension of matrix b  OR<br />
with the given matrix <b>A[i x j]</b> and <b>b[m x n]</b> where <b>j=m</b>.

In [10]:
print(f"Matrix A: {A} \n\nMatrix b: {b} \n\nA*b will be: {Ab} \n\nBroadcast version of A (stay the same) and b: 3x3 and 3x1 -> 3x3")

print("Boradcast b: \n", np.broadcast_to(A, (3,3)))
print("\nBoradcast b: \n", np.broadcast_to(b, (3,3)))


Matrix A: [[8 6 8]
 [6 5 0]
 [7 5 8]] 

Matrix b: [3 9 4] 

A*b will be: [[24 54 32]
 [18 45  0]
 [21 45 32]] 

Broadcast version of A (stay the same) and b: 3x3 and 3x1 -> 3x3
Boradcast b: 
 [[8 6 8]
 [6 5 0]
 [7 5 8]]

Boradcast b: 
 [[3 9 4]
 [3 9 4]
 [3 9 4]]


## Now create a third array `c` that is a (2,) array of random integers.

In [11]:
c = np.random.randint(0, 10, (2,))
c

array([7, 0], dtype=int32)

## Perform the operation `A*c`

In [7]:
Ac = A * c

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

## Explain, in terms of broadcasting, why it was not possible to compute `A*c`

### Your explanation here.

Looking at the matrix's dimenstion we can say that the conditions is not met for the operation. A has (3x3) while c is (2,). Even after applying the first rule by padding the matrix with fewer dimension which c becomes (2, 2), it still doesn't satisfy rule #2 which the shape of the two arrays does not match in any dimension

In [12]:
print("\nBoradcast c: \n", np.broadcast_to(c, (3,3)))

ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,)  and requested shape (3,3)